kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
global:
  smtp_smarthost: 'localhost:1025'
  smtp_from: 'alertmanager@example.org'
  smtp_require_tls: false

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: email
  routes:
  - match:
      severity: critical
    receiver: pager
    routes:
      - match:
          service: application1
        receiver: support_team
  - match_re:
      severity: ^(medium|high)$
    receiver: support_team
receivers:
- name: 'email'
  email_configs:
  - to: 'alerts@example.com'
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
- name: 'support_team'
  email_configs:
  - to: 'support@example.com'
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    text: '{{ .CommonAnnotations.summary }}'
- name: 'pager'
  email_configs:
  - to: 'alert-pager@example.com'
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
