apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    component: core
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: LoadBalancer
  ports:
    - port: 9093
      targetPort: web
      name: web
  selector:
    app: alertmanager
    component: core
