global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - am1:9093
      - am2:9093
      - am3:9093

rule_files:
  - "rules/*_rules.yml"
  - "rules/*_alerts.yml"

scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'alertmanager'
  static_configs:
    - targets: [ 'am1:9093', 'am2:9093', 'am3:9093' ]

- job_name: 'node'
  static_configs:
    - targets: [ 'node_exporter:9100' ]

