apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-rules-conf
  namespace: monitoring
data:
  prometheus_alerts.yml: |
    groups:
    - name: prometheus_alerts
      rules:
      - alert: PrometheusConfigReloadFailed
        expr: prometheus_config_last_reload_successful == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          description: Reloading Prometheus' configuration has failed on {{$labels.instance}}.
      - alert: PrometheusNotConnectedToAlertmanagers
        expr: prometheus_notifications_alertmanagers_discovered < 1
        for: 10m
        labels:
          severity: warning
        annotations:
          description: Prometheus {{ $labels.instance}} is not connected to any Alertmanagers
  node_alerts.yml: |
    groups:
    - name: node_alerts
      rules:
      - alert: HighNodeCPU
        expr: instance:node_cpu:avg_rate5m > 1
        for: 10s
        labels:
          severity: medium
        annotations:
          summary: High Node CPU of {{ humanize $value}}% for 1 hour
      - alert: DiskWillFillIn4Hours
        expr: predict_linear(node_filesystem_free{mountpoint="/"}[1h], 4*3600) < 0
        for: 5m
        labels:
          severity: high
        annotations:
          summary: Disk on {{ $labels.instance }} will fill in approximately 4 hours.
      - alert: InstanceDown
        expr: up{job="node"} == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Host {{ $labels.instance }} is down!
      - alert: InstancesDown
        expr:  avg(up{job="node"}) by (job) < 0.75
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Host {{ $labels.instance }} is down!
      - alert: InstancesGone
        expr:  absent(up{job="node"})
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Host {{ $labels.instance }} is no longer reporting!
          description: Werner Heisenberg says - OMG Where are my instances?
  node_rules.yml: |
    groups:
    - name: node_rules
      rules:
      - record: instance:node_cpu:avg_rate5m
        expr: 100 - avg (irate(node_cpu{job="node",mode="idle"}[5m])) by (instance) * 100
      - record: instance:node_memory_usage:percentage
        expr: (node_memory_MemTotal - (node_memory_MemFree + node_memory_Cached + node_memory_Buffers)) / node_memory_MemTotal * 100
      - record: instance:root:node_filesystem_usage:percentage
        expr: (node_filesystem_size{mountpoint="/"} - node_filesystem_free{mountpoint="/"}) / node_filesystem_size{mountpoint="/"}* 100